### ISSUE TITLE
Job Jamming

### ISSUE THREAD

**Issue by screwrules** [FabModules/fabmodules-html5#12]
Hi,

We are facing a problem with the fab modules when milling or cutting a PCB, the Modela MDX-20 seems to jam in the middle of the build, the spindle will spin but the axis wont move.

Did anyone face this problem before. If so, can you please help?

Thanks in advance,
Bader

**Comment by fibasile** [comment]
It might be a cable issue, closing the issue. Please reopen if you are still facing the same problem.
