### ISSUE TITLE
Wrong speed settings for roland PCB trace 0.010

### ISSUE THREAD

**Issue by puneethrj** [FabModules/fabmodules-html5#17]
I was trying to mill http://academy.cba.mit.edu/classes/electronics_production/lines.png using modela with 0.010 inch bit. When I generated the path and ran the modela, it started machining at high speed causing the bit to break.
The default speed set for 0.010 bit is wrongly set as 4mm/s. This causes anybody using it for the first time with the 0.010 bit to break before he/she realize that the default speed set it too high.  
In compiled version of fabmodules this doesn't happen because the default speed set for the 0.010 bit is 2mm/s. The same setting has to be imported into the this html version of fab modules.

**Comment by fibasile** [comment]
Corrected
