### ISSUE TITLE
Roland SRM-20 SerialException

### ISSUE THREAD

**Issue by feadi** [FabModules/fabmodules-html5#19]
Hello! I'm trying to use the fabmodules with the Roland SRM-20.
Monofab shows up in /dev/usb/lp1
I'm running a local webserver 

<pre><code>python -m SimpleHTTPServer</code></pre>

I edited mod_settings and replaced

<pre><code>["command","mod_print.py /dev/usb/lp2 ';'"],</code></pre>

with

<pre><code>["command","mod_print.py /dev/usb/lp1 ';'"],</code></pre>

I changed permissions for /dev/usb/lp1:

<pre><code>crwxrwxrwx  1 root lp   180, 1 feb 23 21:11 lp1</code></pre>

I made mod_server writable:

<pre><code>drwxrwxr-x  3 fab fab    4096 feb 24 16:50 mod_server</code></pre>

Without the "send command" I get:

<pre><code>executing:  "move_xy.rml"
null
command completed: 
error: /bin/sh: 1: move_xy.rml: not found</code></pre>

If I enter this "send command":

<pre><code>./mod_serial.py /dev/usb/lp1 9600 rtscts     (or dsrdtr)</code></pre>

I get the following message:
[error.txt](https://github.com/FabModules/fabmodules-html5/files/144916/error.txt)

Any suggestions?

Thank you,
Ferdi

**Comment by fibasile** [comment]
I'm closing this since you solved the issue
