### ISSUE TITLE
issue with mime

### ISSUE THREAD

**Issue by HenkATwaag** [FabModules/fabmodules-html5#33]
having issues with mime

Ubuntu Bionic Beaver
node --version v8.9.4

Solved by replacing  mime  to mime-types in  node_modules/node-static/lib/node-static.js
line 7,
<   , mime   = require('mime')
>   , mime   = require('mime-types')                                                                                 

npm install mime-types

=========================================================================
npm start             

> fabmodules-html5@1.0.0 start /home/henk/fabacademy/programs/fabmodules-html5
> PATH=./mod_server/:$PATH node ./mod_server/mod_server.js

listening for connections from 127.0.0.1 on 12345
/home/henk/fabacademy/programs/fabmodules-html5/node_modules/node-static/lib/node-static.js:348
                      mime.lookup(files[0]) ||
                           ^

TypeError: mime.lookup is not a function
    at Server.respond (/home/henk/fabacademy/programs/fabmodules-html5/node_modules/node-static/lib/node-static.js:348:28)
    at /home/henk/fabacademy/programs/fabmodules-html5/node_modules/node-static/lib/node-static.js:146:22
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabmodules-html5@1.0.0 start: `PATH=./mod_server/:$PATH node ./mod_server/mod_server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabmodules-html5@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

==============================================================================

**Comment by ludusrusso** [comment]
Hi, I've got the exact same error. I've solved with this command:

```
npm install mime@1.3.6
```

Hope it helps :D

**Comment by rahji** [comment]
I was able to fix this problem by editing `fabmodules-html5/node_modules/node-static/lib/node-static.js`

I replaced the call to `mime.lookup` with `mime.getType` and I no longer get this error.
