### ISSUE TITLE
FabModules do not work locally when using Chrome

### ISSUE THREAD

**Issue by Madouc** [FabModules/fabmodules-html5#6]
XMLHttpRequest cannot load.

the typical cross origin problem

it does work in Firefox however

**Comment by openp2pdesign** [comment]
Have you tried running it from a local server, like calling `python -m SimpleHTTPServer` from the folder of FabModules?

**Comment by Madouc** [comment]
that would work, but then it would make more sense to actually serve the whole page system from the node server.

at  the moment the workaround is creating a shortcut that starts the index.html in firefox specifically.

**Comment by fibasile** [comment]
Fabmodules is supposed to be working straight from fabmodules.org. For local dev I'm working on a local node.js server, which will also replace the python parte currently used. When this semester is cover lots of improvements will be coming!

—
Fiore BasileMobile. +39 3284576081
Email. fiore.basile@gmail.com
Twitter. @fibasile

http://fablabcascina.org

http://fabconnections.org

http://fibasile.github.io
http://artigianatodigitale.com

**Comment by fibasile** [comment]
Closing this
