### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'home.rml'

### ISSUE THREAD

**Issue by tjfagan** [FabModules/fabmodules-html5#7]
I am trying to install the fabmodules in Ubunu and I ran the server and tried to home the modela MDX-20 and below is what the error is giving me.

Please help.

Terence

fab@fab2:~$ mod_serve 
listening for connections from 127.0.0.1 on 12345
executing: ./mod_serial.py /dev/ttyUSB0 9600 dsrdtr "home.rml"
{ [Error: EACCES, open 'home.rml'] errno: -13, code: 'EACCES', path: 'home.rml' }
command completed: 
error: Traceback (most recent call last):
  File "./mod_serial.py", line 106, in <module>
    f = open(filename)
IOError: [Errno 2] No such file or directory: 'home.rml'

/usr/local/bin/mod_server/mod_server.js:48
               if (err) throw err
                              ^
Error: ENOENT, unlink 'home.rml'
    at Error (native)

PS it may because the nodejs is a pre version. What are your thoughts.

**Comment by fibasile** [comment]
Looks more like a permission problem. Make sure node can write in the folder containing mod_serial.py.

Fiore

—
Fiore BasileMobile. +39 3284576081
Email. fiore.basile@gmail.com
Twitter. @fibasile

http://fablabcascina.org

http://fabconnections.org

http://fibasile.github.io
http://artigianatodigitale.com

**Comment by tjfagan** [comment]
Do you or anyone have good documentation on how I give permissions to node to write to file?

**Comment by fibasile** [comment]
Under linux or osx type in a terminal

sudo chmod 777 /path/to/folder

—
Fiore BasileMobile. +39 3284576081
Email. fiore.basile@gmail.com
Twitter. @fibasile

http://fablabcascina.org

http://fabconnections.org

http://fibasile.github.io
http://artigianatodigitale.com

**Comment by tjfagan** [comment]
Thanks, I got past that. Now I am getting a null and a window pops ups with a pause and cancel button.

Got any ideas.
List below of what I received in terminal.

fab@fab2:/usr/local/bin$ listening for connections from 127.0.0.1 on 12345
executing: ./mod_serial.py /dev/ttyUSB0 9600 dsrdtr "move.rml"
null
command completed:

**Comment by fibasile** [comment]
Which machine are you using? And what OS? Also is it connected to ttyUSB0?

Il mercoledì 10 giugno 2015, Terence notifications@github.com ha scritto:

> Thanks, I got past that. Now I am getting a null and a window pops ups
> with a pause and cancel button.
> 
> Got any ideas.
> List below of what I received in terminal.
> 
> fab@fab2:/usr/local/bin$ listening for connections from 127.0.0.1 on 12345
> executing: ./mod_serial.py /dev/ttyUSB0 9600 dsrdtr "move.rml"
> null
> command completed:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FabModules/fabmodules-html5/issues/7#issuecomment-110876065
> .

## 

## 

Fiore Basile
Mobile. +39 3284576081
Email. fiore.basile@gmail.com
Twitter. @fibasile
http://fablabcascina.org
http://fabconnections.org
http://fibasile.github.io
http://artigianatodigitale.com

**Comment by tjfagan** [comment]
Fiore,

Thank you for the information. It turned out to be the incorrect cable.

Terence

On Fri, Jun 12, 2015 at 2:17 PM, Fiore Basile notifications@github.com
wrote:

> Which machine are you using? And what OS? Also is it connected to ttyUSB0?
> 
> Il mercoledì 10 giugno 2015, Terence notifications@github.com ha
> scritto:
> 
> > Thanks, I got past that. Now I am getting a null and a window pops ups
> > with a pause and cancel button.
> > 
> > Got any ideas.
> > List below of what I received in terminal.
> > 
> > fab@fab2:/usr/local/bin$ listening for connections from 127.0.0.1 on
> > 12345
> > executing: ./mod_serial.py /dev/ttyUSB0 9600 dsrdtr "move.rml"
> > null
> > command completed:
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/FabModules/fabmodules-html5/issues/7#issuecomment-110876065
> > 
> > .
> 
> ## 
> 
> ## 
> 
> Fiore Basile
> Mobile. +39 3284576081
> Email. fiore.basile@gmail.com
> Twitter. @fibasile
> http://fablabcascina.org
> http://fabconnections.org
> http://fibasile.github.io
> http://artigianatodigitale.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FabModules/fabmodules-html5/issues/7#issuecomment-111579396
> .

## 

Terence J Fagan Ph.D.
CEO Creatrex Education,LLC
www.creatrexeducation.com
Facebook https://www.facebook.com/pages/Creatrex-Education/354358578051961

**Comment by fibasile** [comment]
Closing
